export type AssetCategory = 'player' | 'tiles' | 'props' | 'doors' | 'pickups' | 'destructibles' | 'interactables' | 'ui' | 'enemy' | 'boss' | 'vfx' | 'background';
export type AssetLoadType = 'image' | 'spritesheet';
export type AssetEnemyType = 'trooper' | 'drone' | 'mech' | 'scout' | 'turret' | 'sentinel' | 'cryo-beast' | 'foundry-brute' | 'reactor-crawler' | 'void-raven' | 'void-wraith' | 'corrupted-soldier' | 'overgrown-crawler' | 'security-crawler' | 'crystal-drone';
export type AssetBossType = 'reactor-core' | 'crystal-behemoth' | 'cryo-stalker' | 'voidwing-corruptor' | 'void-oracle' | 'foundry-mech' | 'overgrown-corruption' | 'security-interceptor' | 'void-knight' | 'swarm-crawler' | 'chrono-assassin';

export type AssetManifestEntry = {
  key: string;
  path: string;
  rawPath: string;
  loadType: AssetLoadType;
  columns: number;
  rows: number;
  frameWidth: number;
  frameHeight: number;
  width: number;
  height: number;
  category: AssetCategory;
  role?: string;
  theme?: string;
  variant?: string;
  enemyType?: AssetEnemyType;
  bossType?: AssetBossType;
  processed: boolean;
  warnings: string[];
};

export const assetManifest = [
  {
    "key": "player",
    "path": "/assets/processed/player.png",
    "rawPath": "/assets/raw/player-hero-future-failure-5x4.png",
    "loadType": "spritesheet",
    "columns": 5,
    "rows": 4,
    "frameWidth": 280,
    "frameHeight": 280,
    "width": 1400,
    "height": 1120,
    "category": "player",
    "role": "hero",
    "theme": "hero-future-failure",
    "processed": true,
    "warnings": []
  },
  {
    "key": "tiles",
    "path": "/assets/processed/tiles.png",
    "rawPath": "/assets/raw/tiles-industrial-platforms-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "tiles",
    "role": "industrial-platforms",
    "theme": "industrial-platforms",
    "processed": true,
    "warnings": []
  },
  {
    "key": "props",
    "path": "/assets/processed/props.png",
    "rawPath": "/assets/raw/props-lab-machinery-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "props",
    "role": "lab-machinery",
    "theme": "lab-machinery",
    "processed": true,
    "warnings": []
  },
  {
    "key": "doors",
    "path": "/assets/processed/doors.png",
    "rawPath": "/assets/raw/doors-portals-security-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "doors",
    "role": "portals-security",
    "theme": "portals-security",
    "processed": true,
    "warnings": []
  },
  {
    "key": "pickups",
    "path": "/assets/processed/pickups.png",
    "rawPath": "/assets/raw/pickups-health-energy-keycards-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "pickups",
    "role": "health-energy-keycards",
    "theme": "health-energy-keycards",
    "processed": true,
    "warnings": []
  },
  {
    "key": "destructibles",
    "path": "/assets/processed/destructibles.png",
    "rawPath": "/assets/raw/destructibles-crates-barrels-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "destructibles",
    "role": "crates-barrels",
    "theme": "crates-barrels",
    "processed": true,
    "warnings": []
  },
  {
    "key": "interactables",
    "path": "/assets/processed/interactables.png",
    "rawPath": "/assets/raw/interactables-terminals-panels-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "interactables",
    "role": "terminals-panels",
    "theme": "terminals-panels",
    "processed": true,
    "warnings": []
  },
  {
    "key": "ui",
    "path": "/assets/processed/ui.png",
    "rawPath": "/assets/raw/ui-future-failure-hud-panels-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "ui",
    "role": "future-failure-hud-panels",
    "theme": "future-failure-hud-panels",
    "processed": true,
    "warnings": []
  },
  {
    "key": "trooper",
    "path": "/assets/processed/trooper.png",
    "rawPath": "/assets/raw/enemy-trooper-soldier-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "enemy",
    "role": "soldier",
    "theme": "soldier",
    "enemyType": "trooper",
    "processed": true,
    "warnings": []
  },
  {
    "key": "drone",
    "path": "/assets/processed/drone.png",
    "rawPath": "/assets/raw/enemy-drone-flying-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "enemy",
    "role": "flying",
    "theme": "flying",
    "enemyType": "drone",
    "processed": true,
    "warnings": []
  },
  {
    "key": "mech",
    "path": "/assets/processed/mech.png",
    "rawPath": "/assets/raw/enemy-mech-heavy-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "enemy",
    "role": "heavy",
    "theme": "heavy",
    "enemyType": "mech",
    "processed": true,
    "warnings": []
  },
  {
    "key": "tiles-industrial-machinery-set-a-6x6",
    "path": "/assets/processed/tiles-industrial-machinery-set-a-6x6.png",
    "rawPath": "/assets/raw/tiles-industrial-machinery-set-a-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "tiles",
    "role": "industrial-machinery",
    "theme": "industrial-machinery",
    "variant": "set-a",
    "processed": true,
    "warnings": []
  },
  {
    "key": "tiles-industrial-machinery-set-b-6x6",
    "path": "/assets/processed/tiles-industrial-machinery-set-b-6x6.png",
    "rawPath": "/assets/raw/tiles-industrial-machinery-set-b-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "tiles",
    "role": "industrial-machinery",
    "theme": "industrial-machinery",
    "variant": "set-b",
    "processed": true,
    "warnings": []
  },
  {
    "key": "tiles-security-platforms-set-a-6x6",
    "path": "/assets/processed/tiles-security-platforms-set-a-6x6.png",
    "rawPath": "/assets/raw/tiles-security-platforms-set-a-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "tiles",
    "role": "security-platforms",
    "theme": "security-platforms",
    "variant": "set-a",
    "processed": true,
    "warnings": []
  },
  {
    "key": "tiles-security-platforms-set-b-6x6",
    "path": "/assets/processed/tiles-security-platforms-set-b-6x6.png",
    "rawPath": "/assets/raw/tiles-security-platforms-set-b-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "tiles",
    "role": "security-platforms",
    "theme": "security-platforms",
    "variant": "set-b",
    "processed": true,
    "warnings": []
  },
  {
    "key": "props-alien-biolab-flora-set-a-6x6",
    "path": "/assets/processed/props-alien-biolab-flora-set-a-6x6.png",
    "rawPath": "/assets/raw/props-alien-biolab-flora-set-a-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "props",
    "role": "alien-biolab-flora",
    "theme": "alien-biolab-flora",
    "variant": "set-a",
    "processed": true,
    "warnings": []
  },
  {
    "key": "props-alien-biolab-flora-set-b-6x6",
    "path": "/assets/processed/props-alien-biolab-flora-set-b-6x6.png",
    "rawPath": "/assets/raw/props-alien-biolab-flora-set-b-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "props",
    "role": "alien-biolab-flora",
    "theme": "alien-biolab-flora",
    "variant": "set-b",
    "processed": true,
    "warnings": []
  },
  {
    "key": "props-maintenance-cables-set-a-6x6",
    "path": "/assets/processed/props-maintenance-cables-set-a-6x6.png",
    "rawPath": "/assets/raw/props-maintenance-cables-set-a-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "props",
    "role": "maintenance-cables",
    "theme": "maintenance-cables",
    "variant": "set-a",
    "processed": true,
    "warnings": []
  },
  {
    "key": "props-maintenance-cables-set-b-6x6",
    "path": "/assets/processed/props-maintenance-cables-set-b-6x6.png",
    "rawPath": "/assets/raw/props-maintenance-cables-set-b-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "props",
    "role": "maintenance-cables",
    "theme": "maintenance-cables",
    "variant": "set-b",
    "processed": true,
    "warnings": []
  },
  {
    "key": "interactables-reactor-terminals-set-a-6x6",
    "path": "/assets/processed/interactables-reactor-terminals-set-a-6x6.png",
    "rawPath": "/assets/raw/interactables-reactor-terminals-set-a-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "interactables",
    "role": "reactor-terminals",
    "theme": "reactor-terminals",
    "variant": "set-a",
    "processed": true,
    "warnings": []
  },
  {
    "key": "interactables-reactor-terminals-set-b-6x6",
    "path": "/assets/processed/interactables-reactor-terminals-set-b-6x6.png",
    "rawPath": "/assets/raw/interactables-reactor-terminals-set-b-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "interactables",
    "role": "reactor-terminals",
    "theme": "reactor-terminals",
    "variant": "set-b",
    "processed": true,
    "warnings": []
  },
  {
    "key": "interactables-signage-terminals-set-a-6x6",
    "path": "/assets/processed/interactables-signage-terminals-set-a-6x6.png",
    "rawPath": "/assets/raw/interactables-signage-terminals-set-a-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "interactables",
    "role": "signage-terminals",
    "theme": "signage-terminals",
    "variant": "set-a",
    "processed": true,
    "warnings": []
  },
  {
    "key": "interactables-signage-terminals-set-b-6x6",
    "path": "/assets/processed/interactables-signage-terminals-set-b-6x6.png",
    "rawPath": "/assets/raw/interactables-signage-terminals-set-b-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "interactables",
    "role": "signage-terminals",
    "theme": "signage-terminals",
    "variant": "set-b",
    "processed": true,
    "warnings": []
  },
  {
    "key": "enemy-corrupted-soldiers-6x6",
    "path": "/assets/processed/enemy-corrupted-soldiers-6x6.png",
    "rawPath": "/assets/raw/enemy-corrupted-soldiers-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "enemy",
    "role": "s",
    "theme": "corrupted-soldiers",
    "enemyType": "corrupted-soldier",
    "processed": true,
    "warnings": []
  },
  {
    "key": "enemy-cryo-beasts-6x6",
    "path": "/assets/processed/enemy-cryo-beasts-6x6.png",
    "rawPath": "/assets/raw/enemy-cryo-beasts-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "enemy",
    "role": "s",
    "theme": "cryo-beasts",
    "enemyType": "cryo-beast",
    "processed": true,
    "warnings": []
  },
  {
    "key": "enemy-crystal-drones-6x6",
    "path": "/assets/processed/enemy-crystal-drones-6x6.png",
    "rawPath": "/assets/raw/enemy-crystal-drones-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "enemy",
    "role": "s",
    "theme": "crystal-drones",
    "enemyType": "crystal-drone",
    "processed": true,
    "warnings": []
  },
  {
    "key": "enemy-foundry-brutes-6x6",
    "path": "/assets/processed/enemy-foundry-brutes-6x6.png",
    "rawPath": "/assets/raw/enemy-foundry-brutes-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "enemy",
    "role": "s",
    "theme": "foundry-brutes",
    "enemyType": "foundry-brute",
    "processed": true,
    "warnings": []
  },
  {
    "key": "enemy-overgrown-crawlers-6x6",
    "path": "/assets/processed/enemy-overgrown-crawlers-6x6.png",
    "rawPath": "/assets/raw/enemy-overgrown-crawlers-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "enemy",
    "role": "s",
    "theme": "overgrown-crawlers",
    "enemyType": "overgrown-crawler",
    "processed": true,
    "warnings": []
  },
  {
    "key": "enemy-reactor-crawlers-6x6",
    "path": "/assets/processed/enemy-reactor-crawlers-6x6.png",
    "rawPath": "/assets/raw/enemy-reactor-crawlers-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "enemy",
    "role": "s",
    "theme": "reactor-crawlers",
    "enemyType": "reactor-crawler",
    "processed": true,
    "warnings": []
  },
  {
    "key": "enemy-scout-bots-set-a-6x6",
    "path": "/assets/processed/enemy-scout-bots-set-a-6x6.png",
    "rawPath": "/assets/raw/enemy-scout-bots-set-a-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "enemy",
    "role": "bots",
    "theme": "bots",
    "variant": "set-a",
    "enemyType": "scout",
    "processed": true,
    "warnings": []
  },
  {
    "key": "enemy-scout-bots-set-b-6x6",
    "path": "/assets/processed/enemy-scout-bots-set-b-6x6.png",
    "rawPath": "/assets/raw/enemy-scout-bots-set-b-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "enemy",
    "role": "bots",
    "theme": "bots",
    "variant": "set-b",
    "enemyType": "scout",
    "processed": true,
    "warnings": []
  },
  {
    "key": "enemy-security-crawlers-6x6",
    "path": "/assets/processed/enemy-security-crawlers-6x6.png",
    "rawPath": "/assets/raw/enemy-security-crawlers-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "enemy",
    "role": "s",
    "theme": "security-crawlers",
    "enemyType": "security-crawler",
    "processed": true,
    "warnings": []
  },
  {
    "key": "enemy-sentinel-drones-6x6",
    "path": "/assets/processed/enemy-sentinel-drones-6x6.png",
    "rawPath": "/assets/raw/enemy-sentinel-drones-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "enemy",
    "role": "drones",
    "theme": "sentinel-drones",
    "enemyType": "sentinel",
    "processed": true,
    "warnings": []
  },
  {
    "key": "enemy-turrets-security-set-a-6x6",
    "path": "/assets/processed/enemy-turrets-security-set-a-6x6.png",
    "rawPath": "/assets/raw/enemy-turrets-security-set-a-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "enemy",
    "role": "s-security",
    "theme": "security",
    "variant": "set-a",
    "enemyType": "turret",
    "processed": true,
    "warnings": []
  },
  {
    "key": "enemy-turrets-security-set-b-6x6",
    "path": "/assets/processed/enemy-turrets-security-set-b-6x6.png",
    "rawPath": "/assets/raw/enemy-turrets-security-set-b-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "enemy",
    "role": "s-security",
    "theme": "security",
    "variant": "set-b",
    "enemyType": "turret",
    "processed": true,
    "warnings": []
  },
  {
    "key": "enemy-void-ravens-6x6",
    "path": "/assets/processed/enemy-void-ravens-6x6.png",
    "rawPath": "/assets/raw/enemy-void-ravens-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "enemy",
    "role": "s",
    "theme": "void-ravens",
    "enemyType": "void-raven",
    "processed": true,
    "warnings": []
  },
  {
    "key": "enemy-void-wraiths-6x6",
    "path": "/assets/processed/enemy-void-wraiths-6x6.png",
    "rawPath": "/assets/raw/enemy-void-wraiths-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "enemy",
    "role": "s",
    "theme": "void-wraiths",
    "enemyType": "void-wraith",
    "processed": true,
    "warnings": []
  },
  {
    "key": "boss-chrono-assassin-6x6",
    "path": "/assets/processed/boss-chrono-assassin-6x6.png",
    "rawPath": "/assets/raw/boss-chrono-assassin-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "boss",
    "role": "chrono-assassin",
    "theme": "chrono-assassin",
    "bossType": "chrono-assassin",
    "processed": true,
    "warnings": []
  },
  {
    "key": "boss-cryo-stalker-beast-6x6",
    "path": "/assets/processed/boss-cryo-stalker-beast-6x6.png",
    "rawPath": "/assets/raw/boss-cryo-stalker-beast-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "boss",
    "role": "cryo-stalker-beast",
    "theme": "cryo-stalker-beast",
    "bossType": "cryo-stalker",
    "processed": true,
    "warnings": []
  },
  {
    "key": "boss-crystal-behemoth-crawler-6x6",
    "path": "/assets/processed/boss-crystal-behemoth-crawler-6x6.png",
    "rawPath": "/assets/raw/boss-crystal-behemoth-crawler-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "boss",
    "role": "crystal-behemoth-crawler",
    "theme": "crystal-behemoth-crawler",
    "bossType": "crystal-behemoth",
    "processed": true,
    "warnings": []
  },
  {
    "key": "boss-foundry-mech-brute-6x6",
    "path": "/assets/processed/boss-foundry-mech-brute-6x6.png",
    "rawPath": "/assets/raw/boss-foundry-mech-brute-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "boss",
    "role": "foundry-mech-brute",
    "theme": "foundry-mech-brute",
    "bossType": "foundry-mech",
    "processed": true,
    "warnings": []
  },
  {
    "key": "boss-overgrown-corruption-beast-6x6",
    "path": "/assets/processed/boss-overgrown-corruption-beast-6x6.png",
    "rawPath": "/assets/raw/boss-overgrown-corruption-beast-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "boss",
    "role": "overgrown-corruption-beast",
    "theme": "overgrown-corruption-beast",
    "bossType": "overgrown-corruption",
    "processed": true,
    "warnings": []
  },
  {
    "key": "boss-reactor-core-props-set-a-6x6",
    "path": "/assets/processed/boss-reactor-core-props-set-a-6x6.png",
    "rawPath": "/assets/raw/boss-reactor-core-props-set-a-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "boss",
    "role": "reactor-core-props",
    "theme": "reactor-props",
    "variant": "set-a",
    "bossType": "reactor-core",
    "processed": true,
    "warnings": []
  },
  {
    "key": "boss-reactor-core-props-set-b-6x6",
    "path": "/assets/processed/boss-reactor-core-props-set-b-6x6.png",
    "rawPath": "/assets/raw/boss-reactor-core-props-set-b-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "boss",
    "role": "reactor-core-props",
    "theme": "reactor-props",
    "variant": "set-b",
    "bossType": "reactor-core",
    "processed": true,
    "warnings": []
  },
  {
    "key": "boss-security-interceptor-6x6",
    "path": "/assets/processed/boss-security-interceptor-6x6.png",
    "rawPath": "/assets/raw/boss-security-interceptor-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "boss",
    "role": "security-interceptor",
    "theme": "security-interceptor",
    "bossType": "security-interceptor",
    "processed": true,
    "warnings": []
  },
  {
    "key": "boss-swarm-crawler-alpha-6x6",
    "path": "/assets/processed/boss-swarm-crawler-alpha-6x6.png",
    "rawPath": "/assets/raw/boss-swarm-crawler-alpha-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "boss",
    "role": "swarm-crawler-alpha",
    "theme": "swarm-crawler-alpha",
    "bossType": "swarm-crawler",
    "processed": true,
    "warnings": []
  },
  {
    "key": "boss-void-knight-warrior-6x6",
    "path": "/assets/processed/boss-void-knight-warrior-6x6.png",
    "rawPath": "/assets/raw/boss-void-knight-warrior-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "boss",
    "role": "void-knight-warrior",
    "theme": "void-knight-warrior",
    "bossType": "void-knight",
    "processed": true,
    "warnings": []
  },
  {
    "key": "boss-void-oracle-caster-6x6",
    "path": "/assets/processed/boss-void-oracle-caster-6x6.png",
    "rawPath": "/assets/raw/boss-void-oracle-caster-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "boss",
    "role": "void-oracle-caster",
    "theme": "void-oracle-caster",
    "bossType": "void-oracle",
    "processed": true,
    "warnings": []
  },
  {
    "key": "boss-voidwing-corruptor-6x6",
    "path": "/assets/processed/boss-voidwing-corruptor-6x6.png",
    "rawPath": "/assets/raw/boss-voidwing-corruptor-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "boss",
    "role": "voidwing-corruptor",
    "theme": "voidwing-corruptor",
    "bossType": "voidwing-corruptor",
    "processed": true,
    "warnings": []
  },
  {
    "key": "vfx-energy-impact-set-a-6x6",
    "path": "/assets/processed/vfx-energy-impact-set-a-6x6.png",
    "rawPath": "/assets/raw/vfx-energy-impact-set-a-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "vfx",
    "role": "energy-impact",
    "theme": "energy-impact",
    "variant": "set-a",
    "processed": true,
    "warnings": []
  },
  {
    "key": "vfx-energy-impact-set-b-6x6",
    "path": "/assets/processed/vfx-energy-impact-set-b-6x6.png",
    "rawPath": "/assets/raw/vfx-energy-impact-set-b-6x6.png",
    "loadType": "spritesheet",
    "columns": 6,
    "rows": 6,
    "frameWidth": 209,
    "frameHeight": 209,
    "width": 1254,
    "height": 1254,
    "category": "vfx",
    "role": "energy-impact",
    "theme": "energy-impact",
    "variant": "set-b",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-command-hall-sanctuary-14",
    "path": "/assets/processed/background-command-hall-sanctuary-14.png",
    "rawPath": "/assets/raw/background-command-hall-sanctuary-14.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "command-hall-sanctuary",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-corrupted-violet-cavern-13",
    "path": "/assets/processed/background-corrupted-violet-cavern-13.png",
    "rawPath": "/assets/raw/background-corrupted-violet-cavern-13.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "corrupted-violet-cavern",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-cryo-cathedral-waterfall-04",
    "path": "/assets/processed/background-cryo-cathedral-waterfall-04.png",
    "rawPath": "/assets/raw/background-cryo-cathedral-waterfall-04.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "cryo-cathedral-waterfall",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-cryo-lab-ruins-17",
    "path": "/assets/processed/background-cryo-lab-ruins-17.png",
    "rawPath": "/assets/raw/background-cryo-lab-ruins-17.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "cryo-lab-ruins",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-crystal-mine-overpass-18",
    "path": "/assets/processed/background-crystal-mine-overpass-18.png",
    "rawPath": "/assets/raw/background-crystal-mine-overpass-18.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "crystal-mine-overpass",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-crystal-reactor-cavern-11",
    "path": "/assets/processed/background-crystal-reactor-cavern-11.png",
    "rawPath": "/assets/raw/background-crystal-reactor-cavern-11.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "crystal-reactor-cavern",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-data-cathedral-depths-06",
    "path": "/assets/processed/background-data-cathedral-depths-06.png",
    "rawPath": "/assets/raw/background-data-cathedral-depths-06.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "data-cathedral-depths",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-data-temple-core-19",
    "path": "/assets/processed/background-data-temple-core-19.png",
    "rawPath": "/assets/raw/background-data-temple-core-19.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "data-temple-core",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-emergency-molten-core-12",
    "path": "/assets/processed/background-emergency-molten-core-12.png",
    "rawPath": "/assets/raw/background-emergency-molten-core-12.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "emergency-molten-core",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-flooded-reactor-reservoir-08",
    "path": "/assets/processed/background-flooded-reactor-reservoir-08.png",
    "rawPath": "/assets/raw/background-flooded-reactor-reservoir-08.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "flooded-reactor-reservoir",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-fogbound-city-depths-09",
    "path": "/assets/processed/background-fogbound-city-depths-09.png",
    "rawPath": "/assets/raw/background-fogbound-city-depths-09.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "fogbound-city-depths",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-industrial-lab-corridor-20",
    "path": "/assets/processed/background-industrial-lab-corridor-20.png",
    "rawPath": "/assets/raw/background-industrial-lab-corridor-20.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "industrial-lab-corridor",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-maintenance-bridge-bay-16",
    "path": "/assets/processed/background-maintenance-bridge-bay-16.png",
    "rawPath": "/assets/raw/background-maintenance-bridge-bay-16.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "maintenance-bridge-bay",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-molten-foundry-core-07",
    "path": "/assets/processed/background-molten-foundry-core-07.png",
    "rawPath": "/assets/raw/background-molten-foundry-core-07.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "molten-foundry-core",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-overgrown-biolab-garden-10",
    "path": "/assets/processed/background-overgrown-biolab-garden-10.png",
    "rawPath": "/assets/raw/background-overgrown-biolab-garden-10.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "overgrown-biolab-garden",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-overgrown-lab-cavern-01",
    "path": "/assets/processed/background-overgrown-lab-cavern-01.png",
    "rawPath": "/assets/raw/background-overgrown-lab-cavern-01.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "overgrown-lab-cavern",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-reactor-drain-corridor-15",
    "path": "/assets/processed/background-reactor-drain-corridor-15.png",
    "rawPath": "/assets/raw/background-reactor-drain-corridor-15.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "reactor-drain-corridor",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-ruined-megacity-silhouette-03",
    "path": "/assets/processed/background-ruined-megacity-silhouette-03.png",
    "rawPath": "/assets/raw/background-ruined-megacity-silhouette-03.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "ruined-megacity-silhouette",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-storm-citadel-exterior-05",
    "path": "/assets/processed/background-storm-citadel-exterior-05.png",
    "rawPath": "/assets/raw/background-storm-citadel-exterior-05.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "storm-citadel-exterior",
    "processed": true,
    "warnings": []
  },
  {
    "key": "background-voidgate-data-spire-02",
    "path": "/assets/processed/background-voidgate-data-spire-02.png",
    "rawPath": "/assets/raw/background-voidgate-data-spire-02.png",
    "loadType": "image",
    "columns": 1,
    "rows": 1,
    "frameWidth": 1672,
    "frameHeight": 941,
    "width": 1672,
    "height": 941,
    "category": "background",
    "role": "level-background",
    "theme": "voidgate-data-spire",
    "processed": true,
    "warnings": []
  }
] as const satisfies readonly AssetManifestEntry[];
